Rename permit_with_key to permit_with_link_key
I guess the Zigpy project changed this method, so we need to keep up.

Before this change, I got an error like this:

  File "/home/nate/.local/lib/python3.10/site-packages/zigpy_cli/radio.py", line 66, in radio
    app = app_cls(config)
TypeError: Can't instantiate abstract class ControllerApplication with abstract method permit_with_link_key

I assume the method was renamed upstream, so let's just rename it too.